name: Lesyria
version: 1.0
main: com.kronyxgames.lesyria.LesyriaPlugin
api-version: 1.20

commands:
  home:
    description: Teleport to or set your home
    usage: /home [set]
  spawn:
    description: Teleport to spawn or a city
    usage: /spawn [city]
  eco:
    description: Economy commands
    usage: /eco <balance|buy|sell> [args]
  quest:
    description: Quest commands
    usage: /quest <start|complete> <quest_name>